[package]
name = "xtask"
version = "0.0.0"
edition = "2021"

[dependencies]
xtaskops = "0.4.2"
clap = "4.4.5"
gamedata = { path = "../gamedata" }
palette = { path = "../palette" }
resources = { path = "../resources" }
