[package]
name = "mapviewer"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "mapviewer"

[dependencies]
image = "0.24.7"
world.workspace = true
resources.workspace = true
png = "0.16"
rand = "0.8.5"
