[package]
name = "octree"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
gamedata = {path = "../gamedata", version = "0.0.0"}

